# Site settings
title: roboism
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  a podcast about robots and feminism but mostly robots
baseurl: " " # the subpath of your site, e.g. /blog/
url: "http://roboism.fm/" # the base hostname & protocol for your site
twitter_username: roboismcast
github_username:  savannahmillion

# Build settings
markdown: kramdown
